### ISSUE TITLE
ログアウトボタンの追加

### ISSUE THREAD

**Issue by Nelca** [Nelca/sharingTodoFront#7]

**Comment by fjnakamura** [comment]
fixed at https://github.com/Nelca/sharingTodoFront/commit/416a06f9b869f9f5292f7bad9617e9b4860833b8

**Comment by Nelca** [comment]
fixed at https://github.com/Nelca/sharingTodoFront/commit/416a06f9b869f9f5292f7bad9617e9b4860833b8
